import axios from 'axios'
import Head from 'next/head'
import React from 'react'
import SumVolumeChart from '../components/SumVolumeChart'
import styles from '../styles/Home.module.css'
function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Stock market analysis</h1>
        <SumVolumeChart />
      </main>
    </div>
  )
}

export default Home
